# pyrefly: ignore [missing-import]
from fastapi import FastAPI, HTTPException
# pyrefly: ignore [missing-import]
from fastapi.middleware.cors import CORSMiddleware
from pydantic import BaseModel
from supabase import create_client, Client
import pandas as pd
import sqlite3
import os
import re
import json
import urllib.request
from dotenv import load_dotenv

load_dotenv()

app = FastAPI(title="CEO Dashboard API")

# Allow React (running on a different port) to communicate with this API
app.add_middleware(
    CORSMiddleware,
    allow_origins=["http://localhost:5173", "http://127.0.0.1:5173"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

SUPABASE_URL = os.getenv("SUPABASE_URL")
SUPABASE_KEY = os.getenv("SUPABASE_KEY")

if not SUPABASE_URL or not SUPABASE_KEY:
    raise RuntimeError("SUPABASE_URL and SUPABASE_KEY must be set in .env")

supabase: Client = create_client(SUPABASE_URL, SUPABASE_KEY)


# --- Database Helpers ---

def fetch_table(table: str, columns: str = "*") -> pd.DataFrame:
    """Fetch all rows from a Supabase table via the SDK (REST API)."""
    response = supabase.table(table).select(columns).execute()
    return pd.DataFrame(response.data) if response.data else pd.DataFrame()


def run_chat_sql(sql: str) -> pd.DataFrame:
    """
    Execute an arbitrary SELECT statement generated by the LLM.
    Strategy: pull the referenced tables from Supabase via SDK, load them into
    an in-memory SQLite database, then run the SQL there.
    This avoids any direct PostgreSQL connection requirement.
    """
    # Find every table name referenced after FROM or JOIN
    tables = list(set(re.findall(r'\b(?:FROM|JOIN)\s+(\w+)', sql, re.IGNORECASE)))

    conn = sqlite3.connect(":memory:")
    try:
        for table in tables:
            df = fetch_table(table)
            if not df.empty:
                df.to_sql(table, conn, if_exists="replace", index=False)

        clean = sql.rstrip(";")
        result = pd.read_sql_query(clean, conn)
    finally:
        conn.close()

    return result


# --- LLM Helpers ---

def _call_llm(prompt: str, system: str = "", max_tokens: int = 600) -> str:
    api_key = os.getenv("GEMINI_API_KEY")
    if not api_key:
        raise ValueError("API Key missing.")

    model = os.getenv("OPENROUTER_MODEL", "google/gemini-2.5-flash")
    url = "https://openrouter.ai/api/v1/chat/completions"

    headers = {
        "Authorization": f"Bearer {api_key}",
        "Content-Type": "application/json",
        "HTTP-Referer": "http://localhost:8000",
        "X-Title": "CEO Dashboard",
    }

    messages = []
    if system:
        messages.append({"role": "system", "content": system})
    messages.append({"role": "user", "content": prompt})

    payload = {
        "model": model,
        "messages": messages,
        "temperature": 0.2,
        "max_tokens": max_tokens,
    }

    req = urllib.request.Request(
        url,
        data=json.dumps(payload).encode("utf-8"),
        headers=headers,
        method="POST",
    )
    with urllib.request.urlopen(req) as response:
        res_data = json.loads(response.read().decode("utf-8"))
        if "choices" in res_data and len(res_data["choices"]) > 0:
            return res_data["choices"][0]["message"]["content"].strip()
        elif "error" in res_data:
            raise RuntimeError(f"OpenRouter API error: {res_data['error'].get('message')}")
        else:
            raise RuntimeError(f"Unexpected response format: {res_data}")


def clean_sql(sql: str) -> str:
    """Cleans up and auto-corrects table names in the generated SQL statement."""
    cleaned = re.sub(r"\s+", " ", sql).strip().rstrip(";")

    project_cols = ["client_name", "project_name", "partner_lead", "deal_stage", "pipeline_value",
                    "billable_hours", "milestone_status", "blockers_flag", "csat_score", "renewal_intent"]
    employee_cols = ["department", "current_headcount", "active_hirings", "attrition_count"]
    finance_cols  = ["target_revenue", "actual_revenue", "mrr", "arr"]

    if re.search(r"\bfrom\s*$", cleaned, flags=re.IGNORECASE):
        if any(col in cleaned.lower() for col in finance_cols):
            cleaned = re.sub(r"\bfrom\s*$", "FROM finance_sheets", cleaned, flags=re.IGNORECASE)
        elif any(col in cleaned.lower() for col in project_cols):
            cleaned = re.sub(r"\bfrom\s*$", "FROM crm_pipeline_and_projects", cleaned, flags=re.IGNORECASE)
        elif any(col in cleaned.lower() for col in employee_cols):
            cleaned = re.sub(r"\bfrom\s*$", "FROM hrms_data", cleaned, flags=re.IGNORECASE)

    return cleaned + ";"


# --- API Data Models ---

class ChatRequest(BaseModel):
    question: str


class FeedbackRequest(BaseModel):
    message: str


# --- Endpoints ---

@app.get("/api/kpis/latest")
def get_latest_kpis():
    """Returns the top-level KPI strip data."""
    try:
        # Latest finance row
        fin_resp = supabase.table("finance_sheets").select("*").order("month", desc=True).limit(1).execute()
        if not fin_resp.data:
            return {"error": "No financial data"}
        row = fin_resp.data[0]

        target  = float(row["target_revenue"] or 0)
        actual  = float(row["actual_revenue"] or 0)
        mrr     = float(row["mrr"] or 0)
        delta_pct = ((actual - target) / target * 100) if target else 0

        # Average CSAT (exclude 0-score rows)
        csat_resp = supabase.table("crm_pipeline_and_projects").select("csat_score").gt("csat_score", 0).execute()
        scores = [r["csat_score"] for r in (csat_resp.data or []) if r["csat_score"]]
        avg_csat = sum(scores) / len(scores) if scores else 0.0

        # Weighted pipeline
        pipe_resp = supabase.table("crm_pipeline_and_projects").select("deal_stage,pipeline_value").execute()
        weights = {"Closed Won": 1.00, "Negotiation": 0.70, "Proposal": 0.40, "Qualification": 0.20}
        pipeline = sum(
            float(r["pipeline_value"] or 0) * weights.get(r["deal_stage"], 0)
            for r in (pipe_resp.data or [])
            if r["deal_stage"] in weights
        )

        return {
            "month": row["month"],
            "actual_revenue": actual,
            "revenue_delta_pct": round(delta_pct, 1),
            "mrr": mrr,
            "pipeline": round(pipeline, 2),
            "avg_csat": round(avg_csat, 1),
        }
    except Exception as e:
        raise HTTPException(status_code=500, detail=str(e))


@app.get("/api/kpis/history")
def get_kpi_history():
    """Returns the full time-series for the charts."""
    try:
        resp = supabase.table("finance_sheets").select("month,target_revenue,actual_revenue,mrr").order("month").execute()
        records = [
            {
                "month": r["month"],
                "target_revenue": float(r["target_revenue"] or 0),
                "actual_revenue": float(r["actual_revenue"] or 0),
                "mrr": float(r["mrr"] or 0),
            }
            for r in (resp.data or [])
        ]
        return records
    except Exception as e:
        raise HTTPException(status_code=500, detail=str(e))


def fallback_sql_generator(question: str) -> str:
    """Keyword-based query parser to act as a fallback when the LLM is rate-limited."""
    q = question.lower()

    if "billable" in q or "hours" in q:
        return "SELECT project_name, billable_hours, partner_lead FROM crm_pipeline_and_projects ORDER BY billable_hours DESC;"
    if "csat" in q or "score" in q or "satisfied" in q:
        return "SELECT project_name, csat_score, client_name FROM crm_pipeline_and_projects ORDER BY csat_score DESC;"
    if "blocker" in q or "blocked" in q:
        return "SELECT project_name, client_name, partner_lead FROM crm_pipeline_and_projects WHERE blockers_flag = 'Yes';"
    if "delayed" in q or "milestone" in q or "delay" in q:
        return "SELECT project_name, client_name, milestone_status FROM crm_pipeline_and_projects WHERE milestone_status = 'Delayed';"
    if "project" in q:
        return "SELECT project_name, client_name, partner_lead, milestone_status FROM crm_pipeline_and_projects;"
    if "headcount" in q or "employee" in q or "staff" in q or "people" in q:
        if "highest" in q or "max" in q or "most" in q or "top" in q:
            return "SELECT department, current_headcount FROM hrms_data ORDER BY current_headcount DESC LIMIT 1;"
        return "SELECT department, current_headcount, active_hirings, attrition_count FROM hrms_data ORDER BY current_headcount DESC;"
    if "department" in q:
        return "SELECT department, current_headcount FROM hrms_data;"
    if "revenue" in q or "mrr" in q or "financial" in q or "performance" in q:
        return "SELECT month, target_revenue, actual_revenue, mrr FROM finance_sheets ORDER BY month DESC;"
    if "pipeline" in q:
        return "SELECT client_name, project_name, pipeline_value FROM crm_pipeline_and_projects ORDER BY pipeline_value DESC;"

    return None


@app.post("/api/chat")
def ask_data_warehouse(req: ChatRequest):
    """Handles the Natural Language to SQL logic."""
    schema_doc = """
    TABLE finance_sheets (month TEXT, target_revenue NUMERIC, actual_revenue NUMERIC, mrr NUMERIC, arr NUMERIC)
    TABLE hrms_data (department TEXT, current_headcount INTEGER, active_hirings INTEGER, attrition_count INTEGER, month TEXT)
    TABLE crm_pipeline_and_projects (client_name TEXT, project_name TEXT, partner_lead TEXT, deal_stage TEXT, pipeline_value NUMERIC, billable_hours NUMERIC, milestone_status TEXT, blockers_flag TEXT, csat_score NUMERIC, renewal_intent TEXT)
    """

    system = (
        "You are a SQL expert. You must return ONLY a single, valid, single-line "
        "SELECT statement compatible with SQLite. Never include markdown, backticks, or explanations. "
        "Only query tables defined in the schema: finance_sheets, hrms_data, crm_pipeline_and_projects. "
    )

    prompt = f"""DATABASE SCHEMA:
{schema_doc}

USER QUESTION: Which department has the highest headcount?
SQL: SELECT department FROM hrms_data ORDER BY current_headcount DESC LIMIT 1;

USER QUESTION: Which project has the highest billable hours?
SQL: SELECT project_name FROM crm_pipeline_and_projects ORDER BY billable_hours DESC LIMIT 1;

USER QUESTION: {req.question}
SQL:"""

    try:
        raw_sql = _call_llm(prompt, system=system, max_tokens=200).strip()
        raw_sql = raw_sql.replace("```sql", "").replace("```", "").replace("\n", " ").strip()
        raw_sql = clean_sql(raw_sql)
        print(f"\n--- DEBUG: SQL ---\n{raw_sql}\n-----------------\n")
    except Exception as e:
        fallback_sql = fallback_sql_generator(req.question)
        if fallback_sql:
            raw_sql = fallback_sql
            print(f"\n--- DEBUG: FALLBACK SQL ---\n{raw_sql}\n--------------------------\n")
        else:
            return {"sql": None, "answer": f"LLM Generation failed: {str(e)}", "data": []}

    if "INVALID" in raw_sql.upper() or not raw_sql.upper().startswith("SELECT"):
        return {"sql": None, "answer": "Could not map question to database schema.", "data": []}

    # Execute SQL via in-memory SQLite populated from Supabase
    try:
        result_df = run_chat_sql(raw_sql)
        data_json = result_df.to_dict(orient="records")
    except Exception as e:
        return {"sql": raw_sql, "answer": f"Query execution failed: {str(e)}", "data": []}

    # Synthesise a natural-language answer
    try:
        preview = result_df.head(10).to_string(index=False)
        synth_prompt = (
            f"QUESTION: {req.question}\nQUERY RESULTS:\n{preview}\n\n"
            "Summarise the answer in one clear, executive-level sentence. No markdown."
        )
        answer = _call_llm(synth_prompt, max_tokens=120)
        if not answer or answer.startswith("Error:"):
            raise Exception(answer or "Empty response")
    except Exception:
        if len(data_json) == 0:
            answer = "No matching records found."
        elif len(data_json) == 1:
            row = data_json[0]
            pairs = [f"{k.replace('_', ' ').title()}: {v}" for k, v in row.items() if v is not None]
            answer = " | ".join(pairs)
        else:
            cols = list(data_json[0].keys())
            label_col = next((c for c in cols if result_df[c].dtype == object), cols[0])
            num_cols  = [c for c in cols if result_df[c].dtype != object]
            top_label = data_json[0].get(label_col, "")
            if num_cols:
                top_num_col = num_cols[0]
                top_val = data_json[0].get(top_num_col, "")
                answer = (
                    f"{len(data_json)} records found. "
                    f"Top result: {label_col.replace('_', ' ').title()} = '{top_label}' "
                    f"with {top_num_col.replace('_', ' ')} = {top_val}."
                )
            else:
                labels = [str(r.get(label_col, "")) for r in data_json[:5]]
                answer = f"{len(data_json)} records found: {', '.join(labels)}" + (" and more." if len(data_json) > 5 else ".")

    return {"sql": raw_sql, "answer": answer, "data": data_json}


@app.get("/api/briefing")
def get_executive_briefing():
    """Generates the AI Chief of Staff weekly briefing."""
    try:
        # Latest finance snapshot
        fin_resp = supabase.table("finance_sheets").select("*").order("month", desc=True).limit(1).execute()
        fin = fin_resp.data[0] if fin_resp.data else {}

        # Headcount totals
        hc_resp = supabase.table("hrms_data").select("current_headcount,active_hirings,attrition_count").execute()
        hc_rows = hc_resp.data or []
        total_hc      = sum(r["current_headcount"] or 0 for r in hc_rows)
        total_hirings = sum(r["active_hirings"]    or 0 for r in hc_rows)
        total_attrition = sum(r["attrition_count"] or 0 for r in hc_rows)

        # CSAT + projects
        proj_resp = supabase.table("crm_pipeline_and_projects").select("*").execute()
        proj_rows = proj_resp.data or []
        scores    = [r["csat_score"] for r in proj_rows if r.get("csat_score") and r["csat_score"] > 0]
        avg_csat  = sum(scores) / len(scores) if scores else 0.0
        blockers  = [r["project_name"] for r in proj_rows if r.get("blockers_flag") == "Yes"]
        delayed   = [r["project_name"] for r in proj_rows if r.get("milestone_status") == "Delayed"]

        # Total pipeline
        pipeline = sum(float(r["pipeline_value"] or 0) for r in proj_rows)

        snapshot = f"""
        FINANCIAL SNAPSHOT (latest month: {fin.get('month', 'N/A')})
        - Actual Revenue   : ${float(fin.get('actual_revenue', 0) or 0):,.0f}
        - MRR              : ${float(fin.get('mrr', 0) or 0):,.0f}
        - Total Pipeline   : ${pipeline:,.0f}

        PEOPLE
        - Total Headcount  : {total_hc} employees
        - Open Reqs        : {total_hirings}
        - Attrition        : {total_attrition} this period

        DELIVERY
        - Average CSAT     : {avg_csat:.2f}/5.0
        - Projects with blockers : {', '.join(blockers) if blockers else 'None'}
        - Delayed milestones     : {', '.join(delayed)  if delayed  else 'None'}
        """

        system = (
            "You are an elite AI Chief of Staff preparing a concise weekly executive briefing "
            "for the CEO. Your tone is direct, data-driven, and action-oriented. "
            "Structure every response with exactly three sections: "
            "🚀 Macro Highlights, ⚠️ Operational Risks, 🎯 Strategic Recommendations. "
            "Each section should be 2-4 sentences. Never use bullet points inside sections."
        )

        briefing_text = _call_llm(snapshot, system=system, max_tokens=500)
        return {"briefing": briefing_text}
    except Exception as e:
        raise HTTPException(status_code=500, detail=str(e))


@app.post("/api/feedback")
def submit_feedback(req: FeedbackRequest):
    """Saves user feedback to the Supabase feedback table."""
    try:
        supabase.table("feedback").insert({"message": req.message}).execute()
        return {"status": "success"}
    except Exception as e:
        raise HTTPException(status_code=500, detail=str(e))